---
- name: Deploy application
  hosts: app
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/odv/reddit
        version: monolith
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/odv/reddit

  handlers:
  - name: reload puma
    become: true
    systemd: name=puma state=restarted
